"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[󰣇 ](fg:matugen-color3)$username[ ](fg:matugen-color3)$directory[ ](fg:matugen-color1)$git_branch$git_status $nodejs$rust$golang$php$python$lua $cmd_duration$jobs$line_break$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700'
matugen-color1 = '{{colors.primary_fixed_dim.default.hex}}'
matugen-color2 = '{{colors.on_primary.default.hex}}'
matugen-color3 = '{{colors.on_surface_variant.default.hex}}'
matugen-color4 = '{{colors.surface_container.default.hex}}'
matugen-color5 = '{{colors.on_primary.default.hex}}'
matugen-color6 = '{{colors.on_primary.default.hex}}'
matugen-color7 = '{{colors.surface.default.hex}}'
matugen-color8 = '{{colors.primary.default.hex}}'
matugen-color9 = '{{colors.tertiary.default.hex}}'
matugen-color10 = '{{colors.on_primary_fixed.default.hex}}'
matugen-color11 = '{{colors.primary_container.default.hex}}'
matugen-color12 = '{{colors.on_secondary.default.hex}}'

[username]
show_always = true
style_user = "fg:matugen-color3 bold"
style_root = "fg:matugen-color8 bold"
format = "[ $user]($style)"
disabled = false

[directory]
style = "fg:matugen-color1 bold"
format = "[ 󰉋 $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Music" = ""
"Pictures" = ""
"Coding" = "󰨞"

[git_branch]
symbol = ""
format = '[ $symbol $branch](fg:matugen-color9)'

[git_status]
format = '[($all_status$ahead_behind)](fg:matugen-color9)'

[nodejs]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[rust]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[golang]
symbol = "󰟓"
format = '[ $symbol ($version)](fg:matugen-color3)'

[php]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[python]
symbol = ""
format = '[ $symbol ($version)( \($virtualenv\))](fg:matugen-color3)'

[lua]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[cmd_duration]
min_time = 2000
format = '[ 󱎫 $duration](fg:matugen-color9)'

[jobs]
symbol = ""
number_threshold = 1
format = '[ $symbol $number](fg:matugen-color9)'

[time]
disabled = false
time_format = "%R"
format = '[  $time](fg:matugen-color3)'

[character]
success_symbol = "[❯](fg:matugen-color1 bold)"
error_symbol = "[❯](fg:matugen-color8 bold)"
