"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[󰣇 ](fg:matugen-color3)$username[ ](fg:matugen-color3)$directory[ ](fg:matugen-color1)$git_branch$git_status$nodejs$rust$golang$php$line_break$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700'
matugen-color1 = '#87d1ea'
matugen-color2 = '#003542'
matugen-color3 = '#bfc8cc'
matugen-color4 = '#1b2023'
matugen-color5 = '#003542'
matugen-color6 = '#003542'
matugen-color7 = '#0f1416'
matugen-color8 = '#87d1ea'
matugen-color9 = '#c2c4eb'
matugen-color10 = '#001f27'
matugen-color11 = '#004e5f'
matugen-color12 = '#1d333b'

[username]
show_always = true
style_user = "fg:matugen-color3 bold"
style_root = "fg:matugen-color8 bold"
format = "[ $user]($style)"
disabled = false

[directory]
style = "fg:matugen-color1 bold"
format = "[ 󰉋 $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Music" = ""
"Pictures" = ""
"Coding" = "󰨞"

[git_branch]
symbol = ""
format = '[ $symbol $branch](fg:matugen-color9)'

[git_status]
format = '[($all_status$ahead_behind)](fg:matugen-color9)'

[nodejs]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color11)'

[rust]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color8)'

[golang]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color1)'

[php]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color9)'

[time]
disabled = false
time_format = "%R"
format = '[  $time](fg:matugen-color3)'

[character]
success_symbol = "[❯](fg:matugen-color1 bold)"
error_symbol = "[❯](fg:matugen-color8 bold)"
