"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[󰣇 ](fg:matugen-color3)$username[ ](fg:matugen-color3)$directory[ ](fg:matugen-color1)$git_branch$git_status $nodejs$rust$golang$php$python$lua $cmd_duration$jobs$line_break$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700'
matugen-color1 = '#f8b1dd'
matugen-color2 = '#4f1e42'
matugen-color3 = '#d3c2ca'
matugen-color4 = '#251e21'
matugen-color5 = '#4f1e42'
matugen-color6 = '#4f1e42'
matugen-color7 = '#181115'
matugen-color8 = '#f8b1dd'
matugen-color9 = '#f4b9a0'
matugen-color10 = '#36072c'
matugen-color11 = '#693459'
matugen-color12 = '#3f2a37'

[username]
show_always = true
style_user = "fg:matugen-color3 bold"
style_root = "fg:matugen-color8 bold"
format = "[ $user]($style)"
disabled = false

[directory]
style = "fg:matugen-color1 bold"
format = "[ 󰉋 $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Music" = ""
"Pictures" = ""
"Videos" = ""
"Coding" = "󰨞"

[git_branch]
symbol = ""
format = '[ $symbol $branch](fg:matugen-color9)'

[git_status]
format = '[($all_status$ahead_behind)](fg:matugen-color9)'

[nodejs]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[rust]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[golang]
symbol = "󰟓"
format = '[ $symbol ($version)](fg:matugen-color3)'

[php]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[python]
symbol = ""
format = '[ $symbol ($version)( \($virtualenv\))](fg:matugen-color3)'

[lua]
symbol = ""
format = '[ $symbol ($version)](fg:matugen-color3)'

[cmd_duration]
min_time = 2000
format = '[ 󱎫 $duration](fg:matugen-color9)'

[jobs]
symbol = ""
number_threshold = 1
format = '[ $symbol $number](fg:matugen-color9)'

[time]
disabled = false
time_format = "%R"
format = '[  $time](fg:matugen-color3)'

[character]
success_symbol = "[❯](fg:matugen-color1 bold)"
error_symbol = "[❯](fg:matugen-color8 bold)"
